### PR TITLE
Add Github actions workflow to run tests

### PR DESCRIPTION
**Pull request by takluyver**
I think this should run when I open the PR.

### CODE REVIEW

**Comment by philsmt** [comment]
Nice, thanks! Is there anything I need to configure with codecov?

**Comment by takluyver** [comment]
There's nothing you need to configure, and I'm generally fairly happy with the default settings. There's stuff you can configure - e.g. disabling coverage comments on pull requests if you don't find them useful (like the one above, although they're a bit more informative once it has coverage measurements in master to compare against).

The details of what you can configure are here: https://docs.codecov.io/docs/codecovyml-reference

**Comment by philsmt** [comment]
Ah, I was just wondering about the codecov links not working. It seems one can add the repository there explicitly to generate tokens for report upload...?

**Comment by takluyver** [comment]
As far as I know, you don't need a token for public repositories. I think it's just in a slightly odd state at the moment because it's not yet got a coverage report for the master branch.

**Comment by tmichela** [comment]
Small detail I remember, it was necessary to set the [concurrency option](https://github.com/European-XFEL/EXtra-data/blob/master/.coveragerc#L3) on extra-data to get a correct coverage count.

**Comment by philsmt** [comment]
Thanks for entertaining my ignorance, let's get this in.

**Comment by takluyver** [comment]
Codecov: https://app.codecov.io/gh/European-XFEL/pasha/

**Comment by philsmt** [comment]
🤩

**Pull request merged**
